<?php

namespace HZ\Wonja237Bundle\Repository;
use Doctrine\ORM\Query\Expr\Join;
/**
 * ActualiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActualiteRepository extends \Doctrine\ORM\EntityRepository
{

}
