<?php

namespace HZ\Wonja237Bundle\Repository;

/**
 * AutreArtisteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AutreArtisteRepository extends \Doctrine\ORM\EntityRepository
{
}
