<?php

namespace HZ\Wonja237Bundle\Repository;

/**
 * PubliciteDefileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PubliciteDefileRepository extends \Doctrine\ORM\EntityRepository
{
}
