<?php

namespace HZ\Wonja237Bundle\Repository;

/**
 * TestSiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestSiteRepository extends \Doctrine\ORM\EntityRepository
{
}
